import fs from 'node:fs';
import path from 'node:path';

const dir = path.resolve('documentacion/entregables_ieee');
fs.mkdirSync(dir, { recursive: true });
const date = '21 de septiembre de 2026';
const esc = (s) => String(s).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;');
const p = (s) => `<p>${s}</p>`;
const h = (n, s) => `<h2><span>${n}</span>${s}</h2>`;
const h3 = (s) => `<h3>${s}</h3>`;
const list = (items) => `<ul>${items.map((x) => `<li>${x}</li>`).join('')}</ul>`;
const steps = (items) => `<ol>${items.map((x) => `<li>${x}</li>`).join('')}</ol>`;
const table = (head, rows) => `<table><thead><tr>${head.map((x) => `<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map((r) => `<tr>${r.map((x) => `<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
const callout = (title, s) => `<aside><strong>${title}</strong>${s}</aside>`;
const css = `@page{size:Letter;margin:18mm 16mm;@bottom-center{content:"CodePortfolio · Página " counter(page) " de " counter(pages);color:#756b60;font:8pt Arial}}@page:first{@bottom-center{content:""}}*{box-sizing:border-box}html{font:10.2pt/1.45 Arial,sans-serif;color:#29251f}body{margin:0}.cover{min-height:235mm;display:flex;flex-direction:column;justify-content:center;padding:12mm 8mm}.brand{width:24mm;height:24mm;border-radius:7mm;display:grid;place-items:center;background:#6d5735;color:white;font:bold 20pt Consolas}.kicker{margin-top:18mm;color:#8a6f47;font-weight:bold;font-size:8.5pt;letter-spacing:1.8pt}h1{margin:4mm 0;font:500 30pt/1.08 Georgia;color:#201d19}.sub{font:13pt/1.45 Georgia;color:#665f57}.line{width:36mm;height:1.5mm;background:#3f7d5e;margin:7mm 0}h2{break-after:avoid;margin:9mm 0 4mm;padding-bottom:2mm;border-bottom:.35mm solid #d8c9b5;font:19pt Georgia}h2 span{color:#8a6f47;margin-right:2mm}h3{break-after:avoid;margin:6mm 0 2mm;color:#3f6d55;font-size:12pt}p{margin:0 0 3mm;text-align:justify}ul,ol{margin:1.5mm 0 4mm 6mm;padding-left:5mm}li{margin-bottom:1.3mm}table{width:100%;border-collapse:collapse;margin:2.5mm 0 5mm;font-size:8.5pt}thead{display:table-header-group}tr{break-inside:avoid}th{padding:2.2mm;background:#6d5735;color:white;text-align:left;border:.2mm solid #6d5735}td{padding:2mm 2.2mm;vertical-align:top;border:.2mm solid #d9d2c8}tbody tr:nth-child(even) td{background:#f7f4ef}aside{margin:4mm 0;padding:3.2mm 4mm;border-left:1.4mm solid #b36b35;background:#fff4e9}aside strong{display:block;color:#6d5735}code,pre{font-family:Consolas,monospace}.break{break-after:page}`;
function doc(title, subtitle, body) { return `<!doctype html><html lang="es"><head><meta charset="utf-8"><title>${title}</title><style>${css}</style></head><body><section class="cover"><div class="brand">&lt;/&gt;</div><div class="kicker">CODEPORTFOLIO · DOCUMENTACIÓN OPERATIVA</div><h1>${title}</h1><p class="sub">${subtitle}</p><div class="line"></div>${table(['Control','Valor'], [['Proyecto','CodePortfolio — portafolios, comunidad y empleo tech'],['Versión','1.0'],['Fecha de corte',date],['Estado','Propuesto para revisión y aprobación']])}</section><div class="break"></div>${h('Control','del documento')}${table(['Versión','Fecha','Cambio','Elaboró'],[['1.0',date,'Documento inicial contrastado con el repositorio.','Equipo CodePortfolio']])}${body}</body></html>`; }

const user = doc('Manual de Usuario', 'Guía para visitantes y desarrolladores que usan la plataforma.',
  h('1.','Introducción') + p('CodePortfolio permite publicar proyectos de software, descubrir perfiles, interactuar con la comunidad y consultar vacantes. Es una aplicación web; no requiere instalación.') +
  h('2.','Requisitos y acceso') + list(['Usa Chrome, Firefox, Edge o Safari actualizado y una conexión a Internet.', 'En Docker local abre <code>http://localhost:3000</code>.', 'Para registrarte, selecciona Crear cuenta, completa los datos y usa un correo único.', 'Inicia sesión con el correo y contraseña. Cierra sesión cuando uses un equipo compartido.']) +
  h('3.','Navegación') + table(['Sección','Uso'],[['Inicio','Feed de proyectos públicos.'],['Explorar proyectos','Consulta proyectos publicados.'],['Mis proyectos','Crea y administra tu portafolio.'],['Empleos','Consulta vacantes y tus postulaciones.'],['Buscar','Busca proyectos, personas y oportunidades.'],['Notificaciones','Revisa y marca avisos como leídos.'],['Configuración','Actualiza perfil, avatar, contraseña o cuenta.']]) +
  h('4.','Crear un proyecto') + steps(['Abre Mis proyectos y selecciona crear.', 'Escribe título, descripción y enlaces de repositorio o demostración cuando apliquen.', 'Guarda como borrador mientras lo preparas.', 'Cámbialo a publicado para mostrarlo en el perfil y el feed.', 'Desde un proyecto propio puedes editarlo, sustituir su imagen o eliminarlo.']) + callout('Imágenes','Carga JPG, PNG, WEBP o GIF reales de hasta 5 MB. Los borradores no son visibles para otros usuarios.') +
  h('5.','Comunidad, perfiles y empleos') + list(['Abre perfiles para consultar información pública y proyectos publicados.', 'Sigue desarrolladores para verlos en el feed de seguidos.', 'Da o retira una reacción y publica comentarios respetuosos.', 'En Empleos, abre una vacante, selecciona Postular y envía una carta opcional.', 'Revisa Mis postulaciones para conocer su estado. Solo se admite una postulación por usuario y vacante.']) +
  h('6.','Configuración y problemas') + table(['Situación','Acción'],[['No puedo iniciar sesión','Comprueba correo/contraseña y espera si realizaste muchos intentos.'],['No puedo editar un proyecto','Solo la cuenta propietaria puede modificarlo.'],['La imagen falla','Comprueba formato y tamaño máximo.'],['La página parece antigua','Recarga y, si persiste, limpia caché.'],['Quiero cambiar contraseña','Usa Configuración; las sesiones de renovación anteriores se invalidan.'],['Quiero eliminar mi cuenta','Confirma la acción con tu contraseña; es irreversible.']]) );

const technical = doc('Manual Técnico', 'Arquitectura, módulos, configuración y operación de CodePortfolio.',
  h('1.','Propósito') + p('Este manual permite instalar, comprender y evolucionar CodePortfolio según el alcance implementado: SPA React, API REST, PostgreSQL, imágenes persistentes y Docker Compose.') +
  h('2.','Arquitectura') + table(['Capa','Tecnología','Responsabilidad'],[['Presentación','React 19, Vite y Nginx','SPA de acceso, perfiles, proyectos, feed, búsqueda, empleos y configuración.'],['Servicios','ASP.NET Core 8 / C#','API REST, JWT, autorización, validaciones y reglas de negocio.'],['Datos','PostgreSQL 16 + EF Core','Usuarios, roles, proyectos, relaciones, vacantes, postulaciones y tokens.'],['Despliegue','Docker Compose','Servicios db, backend y frontend; volúmenes persistentes.']]) +
  h('3.','Estructura y módulos') + table(['Ruta / módulo','Función'],[['codeportfolio-frontend/','Páginas React, UI, contexto de autenticación, cliente API y Nginx.'],['codeportfolio-backend/','Controladores, DTO, modelos, repositorios, servicios, contexto y migraciones.'],['codeportfolio-backend.Tests/','Pruebas xUnit de JWT, autorización, imágenes y seguridad.'],['/api/auth','Registro, login, refresh y logout.'],['/api/user y /api/profile','Perfil, avatar, contraseña, baja, búsqueda y administración.'],['/api/project, feed, comment, follow','Portafolio e interacciones comunitarias.'],['vacancy, company, application','Vacantes, empresas y postulaciones.']]) +
  h('4.','Configuración y ejecución') + p('Copia <code>.env.example</code> a <code>.env</code> y define las credenciales PostgreSQL, <code>JWT_KEY</code> de al menos 32 bytes y, opcionalmente, el administrador inicial. Desde la raíz ejecuta:') + `<pre>${esc('docker compose up --build\n# frontend: http://localhost:3000\n# API local: http://localhost:5102')}</pre>` + callout('Secretos','No versionar .env, contraseñas, JWT ni respaldos.') +
  h('5.','Seguridad') + list(['BCrypt para contraseñas y hash SHA-256 para refresh tokens.', 'JWT con firma, emisor, audiencia y expiración.', 'Autorización por rol y propiedad de recursos.', 'Rate limit de autenticación: 10 solicitudes/minuto por cliente.', 'Validación binaria de imágenes y límite de 5 MB.', 'CORS explícito, HSTS fuera de desarrollo y respuestas de error neutras.']) +
  h('6.','Cambios y pruebas') + p('Las migraciones de Entity Framework en <code>Migrations/</code> versionan el esquema. Todo cambio de modelo debe revisar su migración y probarse sobre una copia. Antes de integrar cambios, ejecutar lint y build del frontend y las pruebas .NET disponibles:') + `<pre>${esc('cd codeportfolio-frontend && npm ci && npm run lint && npm run build\ndotnet test codeportfolio-backend.Tests/CodePortfolio.Tests.csproj')}</pre>` +
  h('7.','Diagnóstico') + `<pre>${esc('docker compose ps\ndocker compose logs -f backend\ndocker compose logs -f db\ndocker stats')}</pre>` + p('Swagger se publica en Development en <code>/swagger</code>. En producción se requiere proxy TLS y PostgreSQL no debe exponerse a Internet.') );

const maintenance = doc('Manual de Mantenimiento', 'Actividades preventivas, correctivas, respaldo y recuperación.',
  h('1.','Propósito') + p('Mantener CodePortfolio estable, seguro y recuperable. La topología considerada es PostgreSQL 16, API ASP.NET Core 8, frontend Nginx/React y volúmenes Docker.') +
  h('2.','Tipos de mantenimiento') + table(['Tipo','Ejemplo'],[['Preventivo','Revisar espacio, logs, actualizaciones y restauraciones.'],['Correctivo','Resolver una falla de autorización o despliegue.'],['Evolutivo','Incorporar mensajería o panel administrativo visual.'],['Adaptativo','Actualizar imágenes base, TLS o configuración de navegador.']]) +
  h('3.','Cronograma preventivo') + table(['Actividad','Frecuencia','Responsable'],[['Revisar servicios, CPU, RAM y volúmenes','Semanal','Operación'],['Revisar logs de API y base','Semanal','Desarrollo'],['Respaldar DB e imágenes','Diario / RPO aprobado','Operación'],['Revisar vulnerabilidades de paquetes e imágenes','Mensual y antes de liberar','Desarrollo'],['Probar restauración completa','Trimestral y antes de cambios críticos','DBA / Calidad'],['Ejecutar regresión','Cada cambio material','Desarrollo / Calidad']]) +
  h('4.','Incidentes correctivos') + steps(['Registrar fecha, síntoma, impacto, versión y evidencia sin secretos.', 'Clasificar gravedad: crítica, alta, media o baja.', 'Contener la falla y preservar evidencia.', 'Reproducir de forma segura en pruebas.', 'Corregir, ejecutar regresión y solicitar revisión.', 'Desplegar, observar y documentar la causa raíz antes de cerrar.']) +
  h('5.','Diagnóstico y respaldo') + table(['Situación','Comando'],[['Estado','<code>docker compose ps</code>'],['Logs API','<code>docker compose logs -f backend</code>'],['Logs DB','<code>docker compose logs -f db</code>'],['Recursos','<code>docker stats</code>'],['Respaldo lógico','<code>docker compose exec -T db pg_dump -U "$POSTGRES_USER" "$POSTGRES_DB" &gt; codeportfolio_YYYYMMDD.sql</code>']]) + callout('Restauración','Incluye siempre la base de datos y el volumen de imágenes. Restaura primero en un ambiente aislado; nunca sobrescribas producción sin aprobación y punto de recuperación.') +
  h('6.','Despliegue y contingencia') + table(['Evento','Acción inicial'],[['Liberación','Identificar commit/artefacto, confirmar respaldo y ejecutar pruebas de humo.'],['API caída','Revisar estado y logs; comprobar conexión a DB antes de reiniciar.'],['DB no saludable','Evitar escrituras, revisar disco/logs/credenciales y recuperar de forma aislada si hace falta.'],['Fuga posible','Rotar secretos, revocar sesiones, preservar evidencia y evaluar alcance.'],['Acceso indebido','Revocar sesiones, corregir autorización y ejecutar regresión actor-recurso.']]) +
  h('7.','Registro') + table(['Fecha','Tipo','Componente','Actividad / incidente','Resultado','Responsable'],Array.from({length:7},()=>['','','','','',''])) );

fs.writeFileSync(path.join(dir, '07_Manual_Usuario_CodePortfolio.html'), user);
fs.writeFileSync(path.join(dir, '08_Manual_Tecnico_CodePortfolio.html'), technical);
fs.writeFileSync(path.join(dir, '09_Manual_Mantenimiento_CodePortfolio.html'), maintenance);
console.log('Manuales generados en', dir);
